services:
  go-chat-server:
    container_name: go-chat-server
    build:
      context: ./server
      dockerfile: DockerFile
    ports:
      - "8081:8080"
    volumes:
      -./server/cmd/:/root/db

  go-chat-client:
    container_name: go-chat-client
    build:
      context: ./client
      dockerfile: DockerFile
    ports:
      - "5174:5174"
