// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	Jti       string
	UserID    string
	CreatedAt time.Time
	ExpireAt  time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	CreatedAt    time.Time
}
